### ISSUE TITLE
Missing propensity scores in counterfactual files

### ISSUE THREAD

**Issue by strayMat** [IBM-HRL-MLHLS/IBM-Causal-Inference-Benchmarking-Framework#2]
Is there any possibility to add the true propensity score e(x)=P(Z=1|X=x)  to the counterfactual files, alongside to y_0 and y_1 ? 
It is a quantity which intervenes (no pun intended) in a lot of causal estimators and therefore could be very useful for benchmarking.

**Comment by ehudkr** [comment]
Hi Matthieu, first, thanks for your interest. Second, I agree on the importance of having the unobserved propensity-to-treat and that it can be helpful (especially for treatment-centric modelling), but unfortunately it is not available for these simulations.

**Comment by strayMat** [comment]
Hi, that's sad ! 
I am curious on the reason of this missingness. Why is it not available? You did not use a bernoulli to attribute the patient to the treatment ?

**Comment by ehudkr** [comment]
Yeah, it's unfortunate. In practice, there is a stochastic assignment based on each patient's propensity. We just didn't keep track of it since it wasn't the focus of the ACIC 2018 Data Challenge.

**Comment by strayMat** [comment]
If you have the original data generation processes, I can rerun the simulation on my lab cluster to recover the propensity, or would it be irrelevant ?

**Comment by ehudkr** [comment]
I could look it up, but since it's work done at IBM, it can be somewhat problematic to share it. 
However, hopefully soon I will resume working on a causal simulator for [causallib](https://github.com/IBM/causallib), and I'll be happy to share any updates.

**Comment by strayMat** [comment]
Thanks a lot, I was precisely looking into causallib ! Nice work 🤗I might use that instead of acic2018 in a first time :)
